apiVersion: v1
kind: Pod
metadata:
 name: pet.pod
 namespace: default
 labels:
spec:
  containers:
    - name: admin
      image: jithendramuppalla/petapplication:latest
      ports:
        - containerPort: 8080
  nodeSelector:
    node: child1
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
