apiVersion: extensions/v1beta1 
kind: Deployment 
metadata: 
  name: petapp
spec: 
  replicas: 2 
  template: 
    metadata: 
      labels: 
        node: child1
    spec: 
      containers: 
      - name: petapp
        image: jithendramuppalla/petapplication:latest
        ports: 
        - containerPort: 8080
